language: go

os: linux

go:
- "1.13.3"

services: 
- postgresql

before_script:
 - export PGPASSWORD='my_password'; 
 - psql -c 'create database travis_ci_test;' -U postgres

script:
  - go test -v ./...
