
version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db